services:
  server:
    build: .
    working_dir: /app
    volumes:
      - ".:/app"
    env_file:
      - .env
    depends_on:
      - database
      - redis
    networks:
      - app-network

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", $$MYSQL_USER, "--password=$$MYSQL_PASSWORD"]
      timeout: 20s
      retries: 10
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:7.4.1
    ports:
      - "6379:6379"
    networks:
      - app-network
    
volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge